server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Edu19-94
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: SalesService
  config:
    import: configserver:http://localhost:9296
